
const firstData = [
    {id:1, 
    company_logo:"./images2/google.png", 
    job_title:"Technical Database Engineer",
    company_name:"Google",
    is_remote_onsite:"Remote",
    location:"New-York",
    typeof_job:"Fulltime",
    salary: "105k",
    job_description:"Workhand welcomes you to the wonderful world of web development. Here the opportunities to create and grow are endless. Join our dynamic and expanding team as a Front-End Developer and contribute to building the future of web development.",
    job_responsibility:"Developing new user-facing features using React and Headless CMS tools. Building reusable components and front-end libraries for future use Translating designs and airframes into high quality code.",
    educational_requirements:"Bachelor degree to complete any reputations university.",
    experiences:"0-1 years in this field",
    email:"rasel@gmail.com",
    phone:"+8801234898370"
},
    {id:2, 
    company_logo:"./images2/netflix.png", 
    job_title:"Database Engineer",
    company_name:"Netflix",
    is_remote_onsite:"On-site",
    location:"California",
    typeof_job:"Fulltime",
    salary: "115k",
    job_description:"The candidate will be a part of strong technology team|The candidate will be working on new technologies and Azure Data Factory",
    job_responsibility:"Develop new applications using the latest Microsoft technology.Maintain and support progressive changes to existing applications and processes.In collaboration with Project Managers and Business Analysts, review business requirements.",
    educational_requirements:"Bachelor degree to complete any reputations university.",
    experiences:"2 years in this field",
    email:"rasel@gmail.com",
    phone:"+8801234898370"
},
    {id:3, 
    company_logo:"./images2/whatsapp.png", 
    job_title:"Backend Developer",
    company_name:"WhatsApp",
    is_remote_onsite:"Remote",
    location:"California",
    typeof_job:"part-time",
    salary: "90k",
    job_description:"We are continuing the most significant technological upgrade in its history. We are reviewing our systems and processes to simplify them and better align them with the needs of our customers. Come and work within a multidisciplinary team that manages and delivers the projects of the bank of tomorrow",

    job_responsibility:"Java back-end development.Experience with AWS Cloud developmentDevOps.Really critical performance. Good memory management.Rigor in code optimization",

    educational_requirements:"Bachelor degree to complete any reputations university.",
    experiences:"3 years in this field",
    email:"rasel@gmail.com",
    phone:"+8801234898370"
},
    {id:4, 
    company_logo:"./images2/facebook.png", 
    job_title:"Frontend Developer",
    company_name:"Facebook",
    is_remote_onsite:"Remote",
    location:"Canada",
    typeof_job:"Full-time",
    salary: "180k",
    job_description:"As one of Canada’s largest and fastest growing cryptocurrency trading platforms, NDAQ has set the bar high for the country’s Finch industry and is constantly leading the way in terms of security and innovation. We are on a mission to empower more Canadians to unlock the full potential of digital finance.",

    job_responsibility:"Developing new user-facing features using React and Headless CMS tools.Building reusable components and front-end libraries for future use.Translating designs and wireframes into high quality code",

    educational_requirements:"Bachelor degree to complete any reputations university.",
    experiences:"1-2 years in this field",
    email:"rasel@gmail.com",
    phone:"+8801234898370"
},
    {id:5, 
    company_logo:"./images2/microsoft.png", 
    job_title:"Software Engineer",
    company_name:"Microsoft",
    is_remote_onsite:"Onsite",
    location:"Canada",
    typeof_job:"Full-time",
    salary: "190k",
    job_description:"As a data governance senior advisor, you help define and implement data management processes, allowing optimal and secure use of data for the benefit of members and clients, with compliance rules, privacy, privacy policies and security in mind.",

    job_responsibility:"You serve as a specialist advisor and subject matter expert on data governance for stakeholders, and as a resource person and coach for decision making bodies. You interact with many stakeholders working in a wide range of fields to understand and communicate issues and influence decision making.",

    educational_requirements:"Bachelor degree to complete any reputations university.",
    experiences:"1-2 years in this field",
    email:"rasel@gmail.com",
    phone:"+8801234898370"
},
    {id:6, 
    company_logo:"./images2/tesla.png", 
    job_title:"Software Engineer",
    company_name:"Tesla",
    is_remote_onsite:"Remote",
    location:"California",
    typeof_job:"Full-time",
    salary: "190k",
    job_description:"We are looking for the right people — people who want to innovate, achieve, grow and lead. We attract and retain the best talent by investing in our employees and empowering them to develop themselves and their careers.",

    job_responsibility:"Under direct supervision, applies basic reliability engineering knowledge to improve products and services of HES.Assist in developing design specifications and design for reliability analysis.Assist in developing reliability test programs on projects.",

    educational_requirements:"Bachelor degree to complete any reputations university.",
    experiences:"1-2 years in this field",
    email:"rasel@gmail.com",
    phone:"+8801234898370"
},
    {id:7, 
    company_logo:"./images2/instagram.png", 
    job_title:"Frontend Engineer",
    company_name:"Instagram",
    is_remote_onsite:"Remote",
    location:"California",
    typeof_job:"Full-time",
    salary: "90k",
    job_description:"We are looking for the right people — people who want to innovate, achieve, grow and lead. We attract and retain the best talent by investing in our employees and empowering them to develop themselves and their careers.",

    job_responsibility:"Under direct supervision, applies basic reliability engineering knowledge to improve products and services of HES.Assist in developing design specifications and design for reliability analysis.Assist in developing reliability test programs on projects.",

    educational_requirements:"Bachelor degree to complete any reputations university.",
    experiences:"2 years in this field",
    email:"rasel@gmail.com",
    phone:"+8801234898370"
},
    {id:8, 
    company_logo:"./images2/pinterest.png", 
    job_title:"Frontend Engineer",
    company_name:"Pinterest",
    is_remote_onsite:"Onsite",
    location:"New York",
    typeof_job:"Full-time",
    salary: "110k",
    job_description:"We are looking for the right people — people who want to innovate, achieve, grow and lead. We attract and retain the best talent by investing in our employees and empowering them to develop themselves and their careers.",

    job_responsibility:"Under direct supervision, applies basic reliability engineering knowledge to improve products and services of HES.Assist in developing design specifications and design for reliability analysis.Assist in developing reliability test programs on projects.",

    educational_requirements:"Bachelor degree to complete any reputations university.",
    experiences:"2 years in this field",
    email:"rasel@gmail.com",
    phone:"+8801234898370"
},
    {id:9, 
    company_logo:"./images2/meta.png", 
    job_title:"Frontend Engineer",
    company_name:"Meta",
    is_remote_onsite:"Onsite",
    location:"New York",
    typeof_job:"Full-time",
    salary: "150k",
    job_description:"We are looking for the right people — people who want to innovate, achieve, grow and lead. We attract and retain the best talent by investing in our employees and empowering them to develop themselves and their careers.",

    job_responsibility:"Under direct supervision, applies basic reliability engineering knowledge to improve products and services of HES.Assist in developing design specifications and design for reliability analysis.Assist in developing reliability test programs on projects.",

    educational_requirements:"Bachelor degree to complete any reputations university.",
    experiences:"2 years in this field",
    email:"rasel@gmail.com",
    phone:"+8801234898370"
},
    {id:10, 
    company_logo:"./images2/spotify.png", 
    job_title:"Database Engineer",
    company_name:"Spotify",
    is_remote_onsite:"Onsite",
    location:"New York",
    typeof_job:"Full-time",
    salary: "160k",
    job_description:"We are looking for the right people — people who want to innovate, achieve, grow and lead. We attract and retain the best talent by investing in our employees and empowering them to develop themselves and their careers.",

    job_responsibility:"Under direct supervision, applies basic reliability engineering knowledge to improve products and services of HES.Assist in developing design specifications and design for reliability analysis.Assist in developing reliability test programs on projects.",

    educational_requirements:"Bachelor degree to complete any reputations university.",
    experiences:"2 years in this field",
    email:"rasel@gmail.com",
    phone:"+8801234898370"
},
]